[package]
name = "core-grpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
bytes = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
hyper = { version = "1", features = ["client", "http2", "server"] }
hyper-util = { workspace = true, features = ["tokio"] }
prost = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true, features = ["util"] }
tracing = { workspace = true }

[lints.rust]
unsafe_code = "forbid"
